spring:
  data:
    redis:
      host: 192.168.31.201
  datasource:
    name: dataSource
    url: jdbc:postgresql://192.168.31.200:5432/seas_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
logging:
  file:
    path: ./logs
  level:
    root: INFO
    com.izhimu: DEBUG