spring:
  datasource:
    name: dataSource
    url: jdbc:postgresql://192.168.31.243:5432/seas_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: INFO
    com.izhimu: DEBUG
