spring:
  datasource:
    url: jdbc:postgresql://192.168.31.203:5432/seas_db
    username: postgres
    password: 123456
  ai:
    ollama:
      base-url: http://192.168.2.166:11434
      chat:
        model: sam4096/qwen2tools
      embedding:
        model: shaw/dmeta-embedding-zh
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        remove-existing-vector-store-table: true
logging:
  file:
    path: ./logs
  level:
    root: INFO
    com.izhimu: DEBUG