spring:
  datasource:
    url: jdbc:postgresql://192.168.31.203:5432/seas_db
    username: postgres
    password: 123456
logging:
  file:
    path: ./logs
  level:
    root: INFO
    com.izhimu: DEBUG