server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    include: spring,seas
  web:
    resources:
      add-mappings: false
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%3.-3p}) |%clr(%12.12t){magenta}| %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:%3.-3p} |%12.12t| %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    name: ${logging.file.path}/seas.log
  logback:
    rollingpolicy:
      clean-history-on-start: true