server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 10GB
  redis:
    host: 192.168.31.201
    port: 6379
    database: 0
    password: 123456
  datasource:
    name: dataSource
    url: jdbc:postgresql://192.168.31.200:5432/seas_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      logic-delete-field: LOGIC_DEL
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    root: INFO
    oshi.util.platform.windows.WmiQueryHandler: ERROR
seas:
  security:
    supers:
      - admin
      - root
    err-time: 300
    err-num: 5
  minio:
    end-point: http://192.168.31.201:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: seas
    proxy-host: http://127.0.0.1:8080

