server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    redis:
      host: 192.168.31.201
      port: 6379
      database: 0
logging:
  level:
    root: INFO
    com.izhimu: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%3.-3p}) |%clr(%12.12t){magenta}| %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} ${LOG_LEVEL_PATTERN:%3.-3p} |%12.12t| %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    path: ./logs
    name: ${logging.file.path}/seas.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
seas:
  security:
    supers:
      - admin
      - root
    err-time: 300
    err-num: 5
    encrypt-mode: SM2
    token-time: 1800

