server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    host: inner.izhimu.cn
    port: 6379
    database: 0
    password: 123456
seas:
  security:
    supers:
      - admin
      - root
    err-time: 300
    err-num: 5
    encrypt-mode: SM2

