server:
  port:
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seas-ai-hub
    username: postgres
    password: izhimu@8392
  data:
    redis:
      host: localhost
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: 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
      chat:
        options:
          model: qwen/qwen3-235b-a22b:free
logging:
  level:
    root: INFO
    com.izhimu: DEBUG
