server:
  port:
spring:
  datasource:
    url: jdbc:postgresql://192.168.31.223:5432/seas-all
    username: postgres
    password: izhimu@8392
  data:
    redis:
      host: 192.168.31.223
logging:
  level:
    root: INFO
    com.izhimu: DEBUG
