server:
  port:
spring:
  datasource:
    url: jdbc:postgresql://192.168.31.224:5432/seas_ai
    username: postgres
    password: haoran@8392
  data:
    redis:
      host: 192.168.31.224
  ai:
    ollama:
      base-url: http://192.168.2.166:11434
      chat:
        model: sam4096/qwen2tools
      embedding:
        model: shaw/dmeta-embedding-zh
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initialize-schema: true
        remove-existing-vector-store-table: true
logging:
  level:
    root: INFO
    com.izhimu: DEBUG
