seas:
  cache:
    type: redis
  security:
    supers:
      - admin
    err-time: 300
    err-num: 5
    token-time: 1800
  storage:
    minio:
      end-point: http://192.168.31.226:9001
      access-key: minioadmin
      secret-key: minioadmin
      bucket: seas
  log:
    enable-ip-address-query: false