server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    include: spring,seas
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 10GB
  freemarker:
    check-template-location: false
mybatis-plus:
  configuration:
    log-impl: com.izhimu.seas.data.service.impl.LogImpl
  global-config:
    banner: false
    db-config:
      logic-delete-field: LOGIC_DEL
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    oshi.util.platform.windows.WmiQueryHandler: ERROR
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:%3.-3p}) |%clr(%12.12t){magenta}| %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:%3.-3p} |%12.12t| %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  file:
    path: ./logs
    name: ${logging.file.path}/server.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
