seas:
  cache:
    type: redis
  security:
    supers:
      - admin
    err-time: 300
    err-num: 5
    token-timeout: 2592000
    active-timeout:
      web: 1800
  log:
    enable-ip-address-query: false