server:
  port:
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/seas-all
    username: username
    password: password
  data:
    redis:
      host: 127.0.0.1
logging:
  level:
    root: INFO
    com.izhimu: DEBUG
