seas:
  cache:
    type: mem
  security:
    supers:
      - admin
    err-time: 300
    err-num: 5
    token-timeout: 2592000
    active-timeout:
      web: 1800
  storage:
    type: local
    local:
      path: /home/haoran/temp/seas
  log:
    enable-ip-address-query: false