spring:
  datasource:
    name: dataSource
    url: jdbc:postgresql://127.0.0.1:5432/seas_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1
logging:
  file:
    path: ./logs
  level:
    root: INFO
    com.izhimu: DEBUG